language: node_js
node_js:
  - 14.15.4

services:
  - docker

script:
  # Build binary and run test
  - npm install
  # Build docker image
  - docker build -t thomascheuk/sample-app .

before_deploy:
  # Login to docker hub
  - echo "Passw0rd" | docker login -u "thomascheuk" --password-stdin
  # Push image to docker
  - docker push thomascheuk/sample-app

  # Deploy
  # Bluemix / IBM Cloud
deploy:
  - edge: true
    provider: bluemixcloudfoundry
    username: apikey
    password: 9NK0YAy7qGAYZBznkg1zrqlHS5XTU7u8nTv-rE5fRqS-
    organizatvion: owenchen@tw.ibm.com
    region: au-syd
    app_name: sample-app
    api: https://api.au-syd.cf.cloud.ibm.com
    space: cheuk.sydney
    manifest: manifest.yml
    #username: thomas.cheuk@hk1.ibm.com
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    on: 
      all_branches: true