language: node_js
node_js:
  - 14.15.4

services:
  - docker

script:
  # Build binary and run test
  - npm install
  # Build docker image
  - docker build -t thomascheuk/sample-app .

before_deploy:
  # Login to docker hub
  - echo "Passw0rd" | docker login -u "thomascheuk" --password-stdin
  # Push image to docker
  - docker push thomascheuk/sample-app

  # Deploy
  # Bluemix / IBM Cloud
deploy:
  - provider: cloudfoundry
    username: thomas.cheuk@hk1.ibm.com
    #########################
    ## Add BLUEMIX_PASSWORD environment variable to your Travis project's settings
    ## https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    #########################
    password: 5l3MxD2nKmP7WxGzu-Vn6D2fVHx2de9lV5fetJkqpzeh
    organization: owenchen@tw.ibm.com
    space: cheuk.sydney
    region: au-syd
    api: https://api.au-syd.cf.cloud.ibm.com